server:
  port: 10000
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://1.1.1.1:1234/heimdall_admin_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=CTT
    username: foo
    password: bar
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      pool-name: HeimdallDataPool
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        threw-exception-if-not-exist: true
        generate_statistics: false
        show_sql: false
        format_sql: false
        use_sql_comments: false
        order_updates: true
        session_factory:
          statement_inspector: com.luter.heimdall.starter.jpa.Inspectors.ShowCaseInspector
        temp:
          use_jdbc_metadata_defaults: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 1000
        one-indexed-parameters: true
  redis:
    database: 1
    host: 1.1.1.1
    port: 1234
    password: bar
    timeout: 60s
    lettuce:
      pool:
        max-active:  10
        max-idle: 5
        min-idle: 5
        max-wait: 600s